/**
 * Schema History Store — records every schema generated by AI.
 * Each entry stores the full SchemaModel snapshot, the original prompt,
 * and a timestamp. Max 30 entries (oldest removed first).
 */
import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { SchemaModel } from '../types';
import { generateId } from '../utils/id';

export type HistoryEntry = {
  id: string;
  prompt: string;
  schemaName: string;
  entityCount: number;
  relationshipCount: number;
  snapshot: SchemaModel;
  createdAt: number;
};

const MAX_ENTRIES = 30;

type SchemaHistoryState = {
  entries: HistoryEntry[];
};

type SchemaHistoryActions = {
  addEntry: (prompt: string, schema: SchemaModel) => void;
  removeEntry: (id: string) => void;
  clearAll: () => void;
};

export type SchemaHistoryStore = SchemaHistoryState & SchemaHistoryActions;

export const useSchemaHistoryStore = create<SchemaHistoryStore>()(
  persist(
    (set) => ({
      entries: [],

      addEntry: (prompt, schema) => {
        const entry: HistoryEntry = {
          id:                generateId(),
          prompt:            prompt.slice(0, 120),
          schemaName:        schema.name,
          entityCount:       schema.entities.length,
          relationshipCount: schema.relationships.length,
          snapshot:          schema,
          createdAt:         Date.now(),
        };

        set((s) => {
          const entries = [entry, ...s.entries];
          // Keep max entries
          return { entries: entries.slice(0, MAX_ENTRIES) };
        });
      },

      removeEntry: (id) => {
        set((s) => ({ entries: s.entries.filter((e) => e.id !== id) }));
      },

      clearAll: () => set({ entries: [] }),
    }),
    {
      name: 'ai-schema-history',
      partialize: (s) => ({ entries: s.entries }),
    },
  ),
);
